require:
  - rubocop-performance

inherit_gem:
  rubocop-github:
    - config/default.yml

AllCops:
  NewCops: enable
Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Style/MultilineIfModifier:
  Enabled: false
Performance/Detect:
  Enabled: false
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table
  EnforcedLastArgumentHashStyle: always_inspect
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
